version: '3'
services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - dev-module:/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=password
      # - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    ports:
      - "27017:27017"
volumes:
  dev-module: