version: '3'
services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: production
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - MONGO_USER=root
      - MONGO_PASSWORD=password
    command: bash -c "npm run seed && npm run dev"
